[project]
name = "test-task"
version = "0.1.0"
description = "Lets do this"
readme = "README.md"
authors = [{ name = "Zeufo", email = "p.yudin.work@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
  "aiosqlite>=0.22.1",
  "dotenv>=0.9.9",
  "fastapi>=0.141.1",
  "loguru>=0.7.3",
  "pytest>=9.1.1",
  "sqlalchemy>=2.0.52",
]

[tool.ruff]
line-length = 100

[dependency-groups]
dev = [
  "aiosqlite>=0.22.1",
  "httpx>=0.28.1",
  "pytest>=9.1.1",
  "pytest-asyncio>=1.4.0",
]

[tool.pytest.ini_options]
pythonpath = ["app"]
asyncio_mode = "auto"
